# Generated by Django 3.2.16 on 2023-02-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_schedule_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.TimeField(verbose_name='hora'),
        ),
    ]
