# Generated by Django 3.2.16 on 2023-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_schedule_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
